### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by AlexDicy** [Kamebase/Kame#1]
#### TODO
- [ ] Add the option for using hashes instead of the .htaccess
- [ ] Use the template variable in the Page function to change the website content
- [x] Move the "base" tag detector to the "initPage" method (5b02a22)
#### Might-DO
